// <auto-generated />
using System;
using GeekRepository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeekRepository.Data.Migrations.ContentCreator
{
    [DbContext(typeof(ContentCreatorDbContext))]
    partial class ContentCreatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content_creator")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccApprovalEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ArtifactVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactVersionId")
                        .HasDatabaseName("ix_gcc_approval_events_artifact_version_id");

                    b.ToTable("gcc_approval_events", "content_creator");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentArtifactId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreateId")
                        .HasDatabaseName("ix_gcc_artifacts_create_id");

                    b.ToTable("gcc_artifacts", "content_creator");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccArtifactVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text")
                        .HasColumnName("metadata_json");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId")
                        .HasDatabaseName("ix_gcc_artifact_versions_artifact_id");

                    b.ToTable("gcc_artifact_versions", "content_creator");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccCreate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("marketing");

                    b.Property<string>("BriefJson")
                        .HasColumnType("text")
                        .HasColumnName("brief_json");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResearchJson")
                        .HasColumnType("text")
                        .HasColumnName("research_json");

                    b.Property<Guid?>("SiteAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("SiteSectionJson")
                        .HasColumnType("text");

                    b.Property<string>("StartingContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_gcc_creates_client_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_gcc_creates_owner_user_id");

                    b.ToTable("gcc_creates", "content_creator");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccSiteFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AffectedUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<string>("FindingType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SiteAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("SiteAnalysisId")
                        .HasDatabaseName("ix_gcc_site_findings_site_analysis_id");

                    b.HasIndex("SiteAnalysisId", "FindingType")
                        .HasDatabaseName("ix_gcc_site_findings_site_analysis_id_finding_type");

                    b.HasIndex("SiteAnalysisId", "Severity")
                        .HasDatabaseName("ix_gcc_site_findings_site_analysis_id_severity");

                    b.ToTable("gcc_site_findings", "content_creator");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccSiteAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("GapsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeedTopic")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("SeoProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeoProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SiteModelJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .HasDatabaseName("ix_gcc_site_analyses_domain");

                    b.ToTable("gcc_site_analyses", "content_creator");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccSiteFinding", b =>
                {
                    b.HasOne("GeekRepository.Data.Entities.ContentCreator.GccSiteAnalysis", null)
                        .WithMany()
                        .HasForeignKey("SiteAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
