// <auto-generated />
using System;
using GeekRepository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeekRepository.Data.Migrations.ContentCreator
{
    [DbContext(typeof(ContentCreatorDbContext))]
    partial class ContentCreatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content_creator")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccApprovalEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ArtifactVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactVersionId")
                        .HasDatabaseName("ix_gcc_approval_events_artifact_version_id");

                    b.ToTable("gcc_approval_events", "content_creator");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentArtifactId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreateId")
                        .HasDatabaseName("ix_gcc_artifacts_create_id");

                    b.ToTable("gcc_artifacts", "content_creator");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccArtifactVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text")
                        .HasColumnName("metadata_json");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId")
                        .HasDatabaseName("ix_gcc_artifact_versions_artifact_id");

                    b.ToTable("gcc_artifact_versions", "content_creator");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingAddressLine1")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("billing_address_line1");

                    b.Property<string>("BillingAddressLine2")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("billing_address_line2");

                    b.Property<string>("BillingCity")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("billing_city");

                    b.Property<string>("BillingContactName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("billing_contact_name");

                    b.Property<string>("BillingCountry")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("billing_country");

                    b.Property<string>("BillingEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("billing_email");

                    b.Property<string>("BillingPostalCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("billing_postal_code");

                    b.Property<string>("BillingRegion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("billing_region");

                    b.Property<string>("ContactAddressLine1")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contact_address_line1");

                    b.Property<string>("ContactAddressLine2")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contact_address_line2");

                    b.Property<string>("ContactCity")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("contact_city");

                    b.Property<string>("ContactCountry")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("contact_country");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("contact_phone");

                    b.Property<string>("ContactPostalCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("contact_postal_code");

                    b.Property<string>("ContactRegion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("contact_region");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PaymentTermsDays")
                        .HasColumnType("integer")
                        .HasColumnName("payment_terms_days");

                    b.Property<string>("PoReference")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("po_reference");

                    b.Property<string>("PublishApiBaseUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("publish_api_base_url");

                    b.Property<string>("PublishCategoryStrategy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("publish_category_strategy");

                    b.Property<string>("PublishClientIdEnvVar")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("publish_client_id_env_var");

                    b.Property<string>("PublishClientSecretEnvVar")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("publish_client_secret_env_var");

                    b.Property<int?>("PublishDefaultAuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("publish_default_author_id");

                    b.Property<string>("PublishOAuthTokenEndpoint")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("publish_oauth_token_endpoint");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("rate");

                    b.Property<string>("TaxId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tax_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_gcc_clients_name_unique");

                    b.ToTable("gcc_clients", "content_creator", t =>
                        {
                            t.HasCheckConstraint("ck_gcc_clients_currency_iso4217", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_gcc_clients_payment_terms_days", "payment_terms_days >= 0");

                            t.HasCheckConstraint("ck_gcc_clients_rate_positive", "rate IS NULL OR rate > 0");
                        });
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccCreate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("marketing");

                    b.Property<string>("BriefJson")
                        .HasColumnType("text")
                        .HasColumnName("brief_json");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResearchJson")
                        .HasColumnType("text")
                        .HasColumnName("research_json");

                    b.Property<Guid?>("ProjectSiteRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("SiteAnalysisId");

                    b.Property<string>("SiteSectionJson")
                        .HasColumnType("text");

                    b.Property<string>("StartingContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_gcc_creates_client_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_gcc_creates_owner_user_id");

                    b.ToTable("gcc_creates", "content_creator");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccSiteFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AffectedUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<string>("FindingType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SiteAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("SiteAnalysisId")
                        .HasDatabaseName("ix_gcc_site_findings_site_analysis_id");

                    b.HasIndex("SiteAnalysisId", "FindingType")
                        .HasDatabaseName("ix_gcc_site_findings_site_analysis_id_finding_type");

                    b.HasIndex("SiteAnalysisId", "Severity")
                        .HasDatabaseName("ix_gcc_site_findings_site_analysis_id_severity");

                    b.ToTable("gcc_site_findings", "content_creator");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccDeliverable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreateId")
                        .HasColumnType("uuid")
                        .HasColumnName("create_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at_utc");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CreateId")
                        .IsUnique()
                        .HasDatabaseName("ix_gcc_deliverables_create_id_unique");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_gcc_deliverables_project_id");

                    b.ToTable("gcc_deliverables", "content_creator", t =>
                        {
                            t.HasCheckConstraint("ck_gcc_deliverables_delivered_at_matches_status", "(status = 'delivered') = (delivered_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_gcc_deliverables_status", "status IN ('planned', 'in_progress', 'delivered')");
                        });
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("budget");

                    b.Property<string>("BudgetCurrency")
                        .HasColumnType("char(3)")
                        .HasColumnName("budget_currency");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<List<string>>("CompetitorUrls")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("competitor_urls");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Department")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<decimal?>("EstimatedHours")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("estimated_hours");

                    b.Property<DateOnly?>("FinishedDate")
                        .HasColumnType("date")
                        .HasColumnName("finished_date");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<List<string>>("PartnerUrls")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("partner_urls");

                    b.Property<Guid?>("ProjectSiteRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_site_run_id");

                    b.Property<string>("SiteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("site_url");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_gcc_projects_client_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_gcc_projects_idempotency_key_unique");

                    b.HasIndex("ClientId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_gcc_projects_client_id_code_unique")
                        .HasFilter("code IS NOT NULL");

                    b.ToTable("gcc_projects", "content_creator", t =>
                        {
                            t.HasCheckConstraint("ck_gcc_projects_budget_currency_pair", "(budget IS NULL) = (budget_currency IS NULL)");

                            t.HasCheckConstraint("ck_gcc_projects_due_date_after_start", "due_date IS NULL OR due_date >= start_date");

                            t.HasCheckConstraint("ck_gcc_projects_finished_date_after_start", "finished_date IS NULL OR finished_date >= start_date");

                            t.HasCheckConstraint("ck_gcc_projects_finished_date_matches_status", "(status = 'finished') = (finished_date IS NOT NULL)");

                            t.HasCheckConstraint("ck_gcc_projects_status", "status IN ('planned', 'active', 'on_hold', 'finished', 'cancelled')");
                        });
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccProjectLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "OccurredAtUtc")
                        .HasDatabaseName("ix_gcc_project_log_project_id_occurred_at_utc");

                    b.ToTable("gcc_project_log", "content_creator", t =>
                        {
                            t.HasCheckConstraint("ck_gcc_project_log_event_type", "event_type IN ('project_created', 'project_updated', 'project_status_changed')");
                        });
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccSiteAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("GapsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeedTopic")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("SeoProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeoProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SiteModelJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .HasDatabaseName("ix_gcc_site_analyses_domain");

                    b.ToTable("gcc_site_analyses", "content_creator");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssigneeUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("assignee_user_id");

                    b.Property<List<string>>("ContentTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("content_types");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<decimal?>("EstimatedHours")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("estimated_hours");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "ProjectId")
                        .HasName("ak_gcc_tasks_id_project_id");

                    b.HasIndex("ProjectId", "SortOrder")
                        .HasDatabaseName("ix_gcc_tasks_project_id_sort_order");

                    b.ToTable("gcc_tasks", "content_creator", t =>
                        {
                            t.HasCheckConstraint("ck_gcc_tasks_status", "status IN ('todo', 'in_progress', 'done')");
                        });
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccTimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Billable")
                        .HasColumnType("boolean")
                        .HasColumnName("billable");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("InvoicedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invoiced_at_utc");

                    b.Property<int>("Minutes")
                        .HasColumnType("integer")
                        .HasColumnName("minutes");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<decimal?>("RateSnapshot")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("rate_snapshot");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date")
                        .HasColumnName("work_date");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "WorkDate")
                        .HasDatabaseName("ix_gcc_time_entries_project_id_work_date");

                    b.HasIndex("TaskId", "ProjectId");

                    b.ToTable("gcc_time_entries", "content_creator", t =>
                        {
                            t.HasCheckConstraint("ck_gcc_time_entries_billable_has_rate", "billable = false OR (rate_snapshot IS NOT NULL AND currency IS NOT NULL)");

                            t.HasCheckConstraint("ck_gcc_time_entries_minutes_positive", "minutes > 0");
                        });
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccTask", b =>
                {
                    b.HasOne("GeekRepository.Data.Entities.ContentCreator.GccProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccTimeEntry", b =>
                {
                    b.HasOne("GeekRepository.Data.Entities.ContentCreator.GccProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeekRepository.Data.Entities.ContentCreator.GccTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccDeliverable", b =>
                {
                    b.HasOne("GeekRepository.Data.Entities.ContentCreator.GccCreate", null)
                        .WithMany()
                        .HasForeignKey("CreateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeekRepository.Data.Entities.ContentCreator.GccProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccProject", b =>
                {
                    b.HasOne("GeekRepository.Data.Entities.ContentCreator.GccClient", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccProjectLogEntry", b =>
                {
                    b.HasOne("GeekRepository.Data.Entities.ContentCreator.GccProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreator.GccSiteFinding", b =>
                {
                    b.HasOne("GeekRepository.Data.Entities.ContentCreator.GccSiteAnalysis", null)
                        .WithMany()
                        .HasForeignKey("SiteAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
