// <auto-generated />
using System;
using GeekRepository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeekRepository.Data.Migrations.ContentCreatorV2
{
    [DbContext(typeof(ContentCreatorV2DbContext))]
    partial class ContentCreatorV2DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content_creator_v2")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsFirstParty")
                        .HasColumnType("boolean");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_gcc_v2_agents_slug");

                    b.ToTable("gcc_v2_agents", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2AgentAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AfterState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("BeforeState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailJson")
                        .HasColumnType("text");

                    b.Property<string>("RequestId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "CreatedAtUtc")
                        .HasDatabaseName("ix_gcc_v2_agent_audit_agent_created");

                    b.ToTable("gcc_v2_agent_audit_events", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2AgentReviewFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DisposedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ReviewerRationale")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AgentVersionId", "Disposition")
                        .HasDatabaseName("ix_gcc_v2_agent_finding_version_disposition");

                    b.ToTable("gcc_v2_agent_review_findings", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2AgentStageParticipation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AgentVersionId", "Stage", "Role")
                        .IsUnique()
                        .HasDatabaseName("ux_gcc_v2_agent_stage_role");

                    b.ToTable("gcc_v2_agent_stage_participation", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2AgentTestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CancellationRequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimedByInstanceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecoveryCount")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VersionDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AgentVersionId", "QueuedAtUtc")
                        .HasDatabaseName("ix_gcc_v2_agent_test_version_queued");

                    b.HasIndex("Status", "LeaseUntilUtc")
                        .HasDatabaseName("ix_gcc_v2_agent_test_status_lease");

                    b.ToTable("gcc_v2_agent_test_runs", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2AgentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedModelsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AllowedToolsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentTypesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeprecatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelPolicyProfile")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ModelPolicyVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reviewer")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SemanticVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TestResultJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("TestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VersionDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("VersionDigest")
                        .IsUnique()
                        .HasDatabaseName("ux_gcc_v2_agent_versions_digest");

                    b.HasIndex("AgentId", "SemanticVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_gcc_v2_agent_versions_agent_semver");

                    b.ToTable("gcc_v2_agent_versions", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2AgentVersionSkillVersion", b =>
                {
                    b.Property<Guid>("AgentVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("AgentVersionId", "SkillVersionId");

                    b.HasIndex("SkillVersionId");

                    b.ToTable("gcc_v2_agent_version_skills", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2AiVisibilitySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CreateId")
                        .HasDatabaseName("ix_gcc_v2_ai_visibility_snapshots_create_id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_gcc_v2_ai_visibility_snapshots_job_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_gcc_v2_ai_visibility_snapshots_owner_user_id");

                    b.ToTable("gcc_v2_ai_visibility_snapshots", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2BrandKit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DerivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DerivedFromProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("KitJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("VoiceStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("provisional");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_gcc_v2_brand_kits_client_id");

                    b.HasIndex("DerivedFromProfileId")
                        .HasDatabaseName("ix_gcc_v2_brand_kits_derived_from_profile_id");

                    b.ToTable("gcc_v2_brand_kits", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2Brief", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("CreateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FrozenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawBriefJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<string>("TargetKeyword")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CreateId")
                        .HasDatabaseName("ix_gcc_v2_briefs_create_id");

                    b.ToTable("gcc_v2_briefs", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2Create", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ProjectSiteCrawlRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("SelectedAgentVersionIdsJson")
                        .HasColumnType("text");

                    b.Property<string>("SiteSectionJson")
                        .HasColumnType("text");

                    b.Property<string>("SiteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_gcc_v2_creates_owner_user_id");

                    b.ToTable("gcc_v2_creates", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2GuardrailRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("strip");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReplaceWith")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Scope")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("ix_gcc_v2_guardrail_rules_enabled");

                    b.ToTable("gcc_v2_guardrail_rules", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentTeamSnapshotDigest")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AgentTeamSnapshotJson")
                        .HasColumnType("text");

                    b.Property<string>("AgentTeamSnapshotKeyId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AgentTeamSnapshotSignature")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("BriefId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimedByInstanceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("CreateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ProjectSiteCrawlRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<Guid?>("SiteAnalysisProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("plan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("pending");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreateId")
                        .HasDatabaseName("ix_gcc_v2_jobs_create_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_gcc_v2_jobs_owner_user_id");

                    b.HasIndex("Status", "LeaseUntilUtc")
                        .HasDatabaseName("ix_gcc_v2_jobs_status_lease_until_utc");

                    b.ToTable("gcc_v2_jobs", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2JobAgentVersion", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("JobId", "AgentVersionId");

                    b.HasIndex("AgentVersionId");

                    b.ToTable("gcc_v2_job_agent_versions", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2JobEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Seq")
                        .IsUnique()
                        .HasDatabaseName("ux_gcc_v2_job_events_job_id_seq");

                    b.ToTable("gcc_v2_job_events", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2Outline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BriefId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FrozenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HierarchyChildHeadingsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<string>("OutlineJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("BriefId")
                        .HasDatabaseName("ix_gcc_v2_outlines_brief_id");

                    b.ToTable("gcc_v2_outlines", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2ProjectSiteCrawlLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsSameOrigin")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_gcc_v2_project_site_crawl_links_run_id");

                    b.ToTable("gcc_v2_project_site_crawl_links", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2ProjectSiteCrawlPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CrawledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinalUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Html")
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("RobotsAllowed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_gcc_v2_project_site_crawl_pages_run_id");

                    b.HasIndex("RunId", "Url")
                        .HasDatabaseName("ix_gcc_v2_project_site_crawl_pages_run_url");

                    b.ToTable("gcc_v2_project_site_crawl_pages", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2ProjectSiteCrawlRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("HostProgressJson")
                        .HasColumnType("text");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SeedUrlsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("pending");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "SiteUrl", "CreatedAtUtc")
                        .HasDatabaseName("ix_gcc_v2_project_site_crawl_runs_owner_site_created");

                    b.ToTable("gcc_v2_project_site_crawl_runs", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2PublishRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyDocumentJson")
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("blog");

                    b.Property<Guid>("CreateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int?>("ExternalPostId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PublicUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("draft");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreateId")
                        .HasDatabaseName("ix_gcc_v2_publish_records_create_id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_gcc_v2_publish_records_job_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_gcc_v2_publish_records_owner_user_id");

                    b.ToTable("gcc_v2_publish_records", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2SkillApplicability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivationMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ConflictsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredToolsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionId", "Stage", "ContentType")
                        .IsUnique()
                        .HasDatabaseName("ux_gcc_v2_skill_applicability_scope");

                    b.ToTable("gcc_v2_skill_applicabilities", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2SkillAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AfterState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BeforeState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PackageId", "CreatedAtUtc")
                        .HasDatabaseName("ix_gcc_v2_skill_audit_package_created");

                    b.ToTable("gcc_v2_skill_audit_events", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2SkillFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ByteCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionId", "RelativePath")
                        .IsUnique()
                        .HasDatabaseName("ux_gcc_v2_skill_files_version_path");

                    b.ToTable("gcc_v2_skill_files", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2SkillPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeprecatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsFirstParty")
                        .HasColumnType("boolean");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("SourceRepository")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_gcc_v2_skill_packages_slug");

                    b.ToTable("gcc_v2_skill_packages", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2SkillReviewFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("Line")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<bool>("PermanentRejection")
                        .HasColumnType("boolean");

                    b.Property<string>("ReviewerRationale")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Scanner")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("gcc_v2_skill_review_findings", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2SkillVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Compatibility")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ImmutableGitRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ManifestDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<string>("PackageSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reviewer")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SemanticVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("SupersedesVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PackageSha256")
                        .IsUnique()
                        .HasDatabaseName("ux_gcc_v2_skill_versions_package_sha256");

                    b.HasIndex("PackageId", "SemanticVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_gcc_v2_skill_versions_package_semver");

                    b.ToTable("gcc_v2_skill_versions", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2StageResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<string>("SectionKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TokensUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_gcc_v2_stage_results_job_id");

                    b.ToTable("gcc_v2_stage_results", "content_creator_v2");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2AgentReviewFinding", b =>
                {
                    b.HasOne("GeekRepository.Data.Entities.ContentCreatorV2.GccV2AgentVersion", "AgentVersion")
                        .WithMany("Findings")
                        .HasForeignKey("AgentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentVersion");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2AgentStageParticipation", b =>
                {
                    b.HasOne("GeekRepository.Data.Entities.ContentCreatorV2.GccV2AgentVersion", "AgentVersion")
                        .WithMany("StageParticipation")
                        .HasForeignKey("AgentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentVersion");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2AgentTestRun", b =>
                {
                    b.HasOne("GeekRepository.Data.Entities.ContentCreatorV2.GccV2AgentVersion", "AgentVersion")
                        .WithMany("TestRuns")
                        .HasForeignKey("AgentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentVersion");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2AgentVersion", b =>
                {
                    b.HasOne("GeekRepository.Data.Entities.ContentCreatorV2.GccV2Agent", "Agent")
                        .WithMany("Versions")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2AgentVersionSkillVersion", b =>
                {
                    b.HasOne("GeekRepository.Data.Entities.ContentCreatorV2.GccV2AgentVersion", "AgentVersion")
                        .WithMany("Skills")
                        .HasForeignKey("AgentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeekRepository.Data.Entities.ContentCreatorV2.GccV2SkillVersion", "SkillVersion")
                        .WithMany()
                        .HasForeignKey("SkillVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentVersion");

                    b.Navigation("SkillVersion");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2JobAgentVersion", b =>
                {
                    b.HasOne("GeekRepository.Data.Entities.ContentCreatorV2.GccV2AgentVersion", "AgentVersion")
                        .WithMany()
                        .HasForeignKey("AgentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeekRepository.Data.Entities.ContentCreatorV2.GccV2Job", "Job")
                        .WithMany("AgentVersions")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentVersion");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2SkillApplicability", b =>
                {
                    b.HasOne("GeekRepository.Data.Entities.ContentCreatorV2.GccV2SkillVersion", "Version")
                        .WithMany("Applicability")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2SkillFile", b =>
                {
                    b.HasOne("GeekRepository.Data.Entities.ContentCreatorV2.GccV2SkillVersion", "Version")
                        .WithMany("Files")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2SkillReviewFinding", b =>
                {
                    b.HasOne("GeekRepository.Data.Entities.ContentCreatorV2.GccV2SkillVersion", "Version")
                        .WithMany("Findings")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2SkillVersion", b =>
                {
                    b.HasOne("GeekRepository.Data.Entities.ContentCreatorV2.GccV2SkillPackage", "Package")
                        .WithMany("Versions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2Agent", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2AgentVersion", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("Skills");

                    b.Navigation("StageParticipation");

                    b.Navigation("TestRuns");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2Job", b =>
                {
                    b.Navigation("AgentVersions");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2SkillPackage", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.ContentCreatorV2.GccV2SkillVersion", b =>
                {
                    b.Navigation("Applicability");

                    b.Navigation("Files");

                    b.Navigation("Findings");
                });
#pragma warning restore 612, 618
        }
    }
}
