// <auto-generated />
using System;
using GeekRepository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeekRepository.Data.Migrations.ContentWriter
{
    [DbContext(typeof(ContentWriterDbContext))]
    [Migration("20260719211339_InitialWebPost")]
    partial class InitialWebPost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeekRepository.Data.Entities.WebPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("web_posts", "public");
                });

            modelBuilder.Entity("GeekRepository.Data.Entities.WebPost", b =>
                {
                    b.OwnsOne("GeekRepository.Data.Entities.ContentStructure", "ContentStructure", b1 =>
                        {
                            b1.Property<Guid>("WebPostId");

                            b1.Property<string>("MainBody");

                            b1.HasKey("WebPostId");

                            b1.ToTable("web_posts", "public");

                            b1
                                .ToJson("content_structure")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WebPostId");

                            b1.OwnsMany("GeekRepository.Data.Entities.ContentSection", "Sections", b2 =>
                                {
                                    b2.Property<Guid>("ContentStructureWebPostId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("BodyContent")
                                        .IsRequired();

                                    b2.Property<string>("HeadingText");

                                    b2.Property<string>("MediaAlt");

                                    b2.Property<string>("MediaUrl");

                                    b2.HasKey("ContentStructureWebPostId", "__synthesizedOrdinal");

                                    b2.ToTable("web_posts", "public");

                                    b2.WithOwner()
                                        .HasForeignKey("ContentStructureWebPostId");
                                });

                            b1.Navigation("Sections");
                        });

                    b.Navigation("ContentStructure")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
