// <auto-generated />
using System;
using GeekBackend.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeekBackend.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("GeekBackend.Data.Models.CaseStudy", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("id");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<DateTime?>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");
            b.Property<string>("DescriptiveName")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("character varying(255)")
                .HasColumnName("descriptive_name");
            b.Property<string>("Exceptions")
                .HasColumnType("text")
                .HasColumnName("exceptions");
            b.Property<string>("ExecutiveSummary")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("executive_summary");
            b.Property<string>("IndustryCitation")
                .HasMaxLength(150)
                .HasColumnType("character varying(150)")
                .HasColumnName("industry_citation");
            b.Property<string>("PostConditions")
                .HasColumnType("text")
                .HasColumnName("post_conditions");
            b.Property<string>("PrimaryActor")
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnType("character varying(150)")
                .HasColumnName("primary_actor");
            b.Property<string>("ProblemChallenge")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("problem_challenge");
            b.Property<DateTime?>("PublishedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("published_at");
            b.Property<string>("Slug")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("character varying(255)")
                .HasColumnName("slug");
            b.Property<string>("Solution")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("solution");
            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("draft")
                .HasColumnType("character varying(20)")
                .HasColumnName("status");
            b.Property<string>("Trigger")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("trigger");
            b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");
            b.HasKey("Id");
            b.HasIndex("Slug").IsUnique();
            b.ToTable("case_studies");
        });

        modelBuilder.Entity("GeekBackend.Data.Models.CaseStudyActor", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("id");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("ActorName")
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnType("character varying(150)")
                .HasColumnName("actor_name");
            b.Property<string>("ActorRole")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)")
                .HasColumnName("actor_role");
            b.Property<int>("CaseStudyId")
                .HasColumnType("integer")
                .HasColumnName("case_study_id");
            b.Property<int>("SortOrder")
                .HasDefaultValue(0)
                .HasColumnType("integer")
                .HasColumnName("sort_order");
            b.HasKey("Id");
            b.HasIndex("CaseStudyId");
            b.ToTable("case_study_actors");
        });

        modelBuilder.Entity("GeekBackend.Data.Models.CaseStudyEventFlowStep", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("id");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<int>("CaseStudyId")
                .HasColumnType("integer")
                .HasColumnName("case_study_id");
            b.Property<int?>("StepActorId")
                .HasColumnType("integer")
                .HasColumnName("step_actor_id");
            b.Property<string>("StepDescription")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("step_description");
            b.Property<int>("StepNumber")
                .HasColumnType("integer")
                .HasColumnName("step_number");
            b.HasKey("Id");
            b.HasIndex("StepActorId");
            b.HasIndex("CaseStudyId", "StepNumber").IsUnique();
            b.ToTable("case_study_event_flow_steps");
        });

        modelBuilder.Entity("GeekBackend.Data.Models.CaseStudyMetric", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("id");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<int>("CaseStudyId")
                .HasColumnType("integer")
                .HasColumnName("case_study_id");
            b.Property<string>("MetricLabel")
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnType("character varying(150)")
                .HasColumnName("metric_label");
            b.Property<string>("MetricUnit")
                .HasMaxLength(50)
                .HasColumnType("character varying(50)")
                .HasColumnName("metric_unit");
            b.Property<string>("MetricValue")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)")
                .HasColumnName("metric_value");
            b.Property<int>("SortOrder")
                .HasDefaultValue(0)
                .HasColumnType("integer")
                .HasColumnName("sort_order");
            b.HasKey("Id");
            b.HasIndex("CaseStudyId");
            b.ToTable("case_study_metrics");
        });

        modelBuilder.Entity("GeekBackend.Data.Models.Department", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("id");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<DateTime>("CreatedAt")
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");
            b.Property<string>("Description")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("description");
            b.Property<string>("IconName")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("icon_name");
            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("name");
            b.Property<string>("Slug")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("slug");
            b.Property<int>("SortOrder")
                .HasDefaultValue(0)
                .HasColumnType("integer")
                .HasColumnName("sort_order");
            b.HasKey("Id");
            b.HasIndex("Slug").IsUnique();
            b.ToTable("departments");
        });

        modelBuilder.Entity("GeekBackend.Data.Models.UseCase", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("id");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<int?>("CaseStudyId")
                .HasColumnType("integer")
                .HasColumnName("case_study_id");
            b.Property<DateTime?>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");
            b.Property<int>("DepartmentId")
                .HasColumnType("integer")
                .HasColumnName("department_id");
            b.Property<string>("DescriptiveName")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("character varying(255)")
                .HasColumnName("descriptive_name");
            b.Property<string>("Slug")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("character varying(255)")
                .HasColumnName("slug");
            b.Property<string>("Summary")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("summary");
            b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");
            b.HasKey("Id");
            b.HasIndex("CaseStudyId");
            b.HasIndex("DepartmentId");
            b.HasIndex("Slug").IsUnique();
            b.ToTable("use_cases");
        });

        modelBuilder.Entity("GeekBackend.Data.Models.CaseStudyActor", b =>
        {
            b.HasOne("GeekBackend.Data.Models.CaseStudy", "CaseStudy")
                .WithMany("CaseStudyActors")
                .HasForeignKey("CaseStudyId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("CaseStudy");
        });

        modelBuilder.Entity("GeekBackend.Data.Models.CaseStudyEventFlowStep", b =>
        {
            b.HasOne("GeekBackend.Data.Models.CaseStudy", "CaseStudy")
                .WithMany("CaseStudyEventFlowSteps")
                .HasForeignKey("CaseStudyId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.HasOne("GeekBackend.Data.Models.CaseStudyActor", "StepActor")
                .WithMany("CaseStudyEventFlowSteps")
                .HasForeignKey("StepActorId")
                .OnDelete(DeleteBehavior.SetNull);
            b.Navigation("CaseStudy");
            b.Navigation("StepActor");
        });

        modelBuilder.Entity("GeekBackend.Data.Models.CaseStudyMetric", b =>
        {
            b.HasOne("GeekBackend.Data.Models.CaseStudy", "CaseStudy")
                .WithMany("CaseStudyMetrics")
                .HasForeignKey("CaseStudyId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("CaseStudy");
        });

        modelBuilder.Entity("GeekBackend.Data.Models.UseCase", b =>
        {
            b.HasOne("GeekBackend.Data.Models.CaseStudy", "CaseStudy")
                .WithMany("UseCases")
                .HasForeignKey("CaseStudyId")
                .OnDelete(DeleteBehavior.SetNull);
            b.HasOne("GeekBackend.Data.Models.Department", "Department")
                .WithMany("UseCases")
                .HasForeignKey("DepartmentId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
            b.Navigation("CaseStudy");
            b.Navigation("Department");
        });

        modelBuilder.Entity("GeekBackend.Data.Models.CaseStudy", b =>
        {
            b.Navigation("CaseStudyActors");
            b.Navigation("CaseStudyEventFlowSteps");
            b.Navigation("CaseStudyMetrics");
            b.Navigation("UseCases");
        });

        modelBuilder.Entity("GeekBackend.Data.Models.CaseStudyActor", b =>
        {
            b.Navigation("CaseStudyEventFlowSteps");
        });

        modelBuilder.Entity("GeekBackend.Data.Models.Department", b =>
        {
            b.Navigation("UseCases");
        });
#pragma warning restore 612, 618
    }
}
