namespace GeekRepository.Data.Entities.ContentWriterV2;

/// <summary>
/// Cached, tool-intrinsic content (Overview + capabilities) for one real-world product/platform
/// (e.g. "Zapier"), shared across every project/department that mentions it — the same tool gets
/// regenerated by content-writer-v2's ToolPageGenerator from scratch per department otherwise,
/// even though the factual overview/capabilities don't change. Department-specific framing
/// ("how an implementer helps") and metadata are NOT cached here — those stay project-specific
/// and are always regenerated fresh.
/// </summary>
public class ToolContentCache
{
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>Canonicalized tool name (lowercase, trimmed, legal-suffix-stripped) — the lookup key.</summary>
    public string NormalizedToolName { get; set; } = string.Empty;

    /// <summary>Display name as it should be shown/reused verbatim (the first generation's casing).</summary>
    public string DisplayName { get; set; } = string.Empty;

    /// <summary>Serialized shared Section subtree — the h3 overview + capability-list content only.</summary>
    public string OverviewJson { get; set; } = "{}";

    public DateTime UpdatedAtUtc { get; set; } = DateTime.UtcNow;
}
