// <auto-generated />
using System;
using GeekRepository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeekRepository.Migrations.Seo
{
    [DbContext(typeof(SeoDbContext))]
    [Migration("20260519135803_InitialSeoSchema")]
    partial class InitialSeoSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("geek_seo")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alert_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_seo_alerts");

                    b.ToTable("seo_alerts", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_prefix");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_seo_api_keys");

                    b.ToTable("seo_api_keys", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoBackgroundJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("ResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_seo_background_jobs");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_seo_background_jobs_user_id_status");

                    b.ToTable("seo_background_jobs", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoBrandVoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SampleText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sample_text");

                    b.Property<string>("StyleInstructions")
                        .HasColumnType("text")
                        .HasColumnName("style_instructions");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_seo_brand_voices");

                    b.ToTable("seo_brand_voices", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoBulkJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("integer")
                        .HasColumnName("completed_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeywordsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keywords_json");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_seo_bulk_jobs");

                    b.ToTable("seo_bulk_jobs", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoCannibalizationIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompetingUrlsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("competing_urls_json");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keyword");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.HasKey("Id")
                        .HasName("pk_seo_cannibalization_issues");

                    b.ToTable("seo_cannibalization_issues", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoCompetitorPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_text");

                    b.Property<DateTimeOffset>("CrawledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("crawled_at");

                    b.Property<string>("Domain")
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("ExternalLinkCount")
                        .HasColumnType("integer")
                        .HasColumnName("external_link_count");

                    b.Property<bool>("HasStructuredData")
                        .HasColumnType("boolean")
                        .HasColumnName("has_structured_data");

                    b.Property<string>("HeadingsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headings_json");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("http_status");

                    b.Property<int>("ImageCount")
                        .HasColumnType("integer")
                        .HasColumnName("image_count");

                    b.Property<int>("ImagesMissingAlt")
                        .HasColumnType("integer")
                        .HasColumnName("images_missing_alt");

                    b.Property<int>("InternalLinkCount")
                        .HasColumnType("integer")
                        .HasColumnName("internal_link_count");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("text")
                        .HasColumnName("meta_description");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("text")
                        .HasColumnName("meta_title");

                    b.Property<Guid>("SerpResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("serp_result_id");

                    b.Property<string>("StructuredDataTypesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("structured_data_types_json");

                    b.Property<string>("TermsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("terms_json");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer")
                        .HasColumnName("word_count");

                    b.HasKey("Id")
                        .HasName("pk_seo_competitor_pages");

                    b.HasIndex("SerpResultId", "Url")
                        .IsUnique()
                        .HasDatabaseName("ix_seo_competitor_pages_serp_result_id_url");

                    b.ToTable("seo_competitor_pages", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoContentDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("AiDetectionScore")
                        .HasColumnType("numeric")
                        .HasColumnName("ai_detection_score");

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_html");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastScoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scored_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int?>("PublishedScore")
                        .HasColumnType("integer")
                        .HasColumnName("published_score");

                    b.Property<int?>("PublishedWordCount")
                        .HasColumnType("integer")
                        .HasColumnName("published_word_count");

                    b.Property<string>("ScoreComponentsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("score_components_json");

                    b.Property<int>("SeoScore")
                        .HasColumnType("integer")
                        .HasColumnName("seo_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TargetKeyword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_keyword");

                    b.Property<string>("TargetLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_location");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer")
                        .HasColumnName("word_count");

                    b.HasKey("Id")
                        .HasName("pk_seo_content_documents");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_seo_content_documents_project_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_seo_content_documents_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_seo_content_documents_user_id");

                    b.ToTable("seo_content_documents", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoContentPerformanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Clicks")
                        .HasColumnType("integer")
                        .HasColumnName("clicks");

                    b.Property<decimal>("Ctr")
                        .HasColumnType("numeric")
                        .HasColumnName("ctr");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("Impressions")
                        .HasColumnType("integer")
                        .HasColumnName("impressions");

                    b.Property<decimal?>("Position")
                        .HasColumnType("numeric")
                        .HasColumnName("position");

                    b.Property<Guid>("PublishedPageId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_page_id");

                    b.HasKey("Id")
                        .HasName("pk_seo_content_performance_snapshots");

                    b.HasIndex("PublishedPageId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_seo_content_performance_snapshots_published_page_id_date");

                    b.ToTable("seo_content_performance_snapshots", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoGa4Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<byte[]>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_refresh_token");

                    b.Property<byte[]>("EncryptionIv")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encryption_iv");

                    b.Property<byte[]>("EncryptionTag")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encryption_tag");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("property_id");

                    b.HasKey("Id")
                        .HasName("pk_seo_ga4_connections");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_seo_ga4_connections_project_id");

                    b.ToTable("seo_ga4_connections", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoGeoMentionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<bool>("Mentioned")
                        .HasColumnType("boolean")
                        .HasColumnName("mentioned");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<Guid>("QueryId")
                        .HasColumnType("uuid")
                        .HasColumnName("query_id");

                    b.Property<string>("Snippet")
                        .HasColumnType("text")
                        .HasColumnName("snippet");

                    b.HasKey("Id")
                        .HasName("pk_seo_geo_mention_snapshots");

                    b.HasIndex("QueryId")
                        .HasDatabaseName("ix_seo_geo_mention_snapshots_query_id");

                    b.ToTable("seo_geo_mention_snapshots", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoGeoTrackingQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("PlatformsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platforms_json");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_text");

                    b.HasKey("Id")
                        .HasName("pk_seo_geo_tracking_queries");

                    b.ToTable("seo_geo_tracking_queries", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoGscConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<byte[]>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_refresh_token");

                    b.Property<byte[]>("EncryptionIv")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encryption_iv");

                    b.Property<byte[]>("EncryptionTag")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encryption_tag");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("site_url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_seo_gsc_connections");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_seo_gsc_connections_project_id");

                    b.ToTable("seo_gsc_connections", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoKeyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cached_at");

                    b.Property<Guid?>("ClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cluster_id");

                    b.Property<string>("Intent")
                        .HasColumnType("text")
                        .HasColumnName("intent");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keyword");

                    b.Property<decimal?>("KeywordDifficulty")
                        .HasColumnType("numeric")
                        .HasColumnName("keyword_difficulty");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int?>("SearchVolume")
                        .HasColumnType("integer")
                        .HasColumnName("search_volume");

                    b.HasKey("Id")
                        .HasName("pk_seo_keywords");

                    b.ToTable("seo_keywords", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoKeywordCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("AverageDifficulty")
                        .HasColumnType("numeric")
                        .HasColumnName("average_difficulty");

                    b.Property<int>("AverageVolume")
                        .HasColumnType("integer")
                        .HasColumnName("average_volume");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeywordsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keywords_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PillarKeyword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pillar_keyword");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_seo_keyword_clusters");

                    b.ToTable("seo_keyword_clusters", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_seo_organizations");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_seo_organizations_slug");

                    b.ToTable("seo_organizations", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoOrganizationMember", b =>
                {
                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("OrgId", "UserId")
                        .HasName("pk_seo_organization_members");

                    b.ToTable("seo_organization_members", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoPageAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AuditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audited_at");

                    b.Property<string>("IssuesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issues_json");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metadata_json");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_seo_page_audits");

                    b.ToTable("seo_page_audits", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoPlagiarismCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<decimal>("MatchPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("match_percent");

                    b.Property<string>("MatchesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("matches_json");

                    b.HasKey("Id")
                        .HasName("pk_seo_plagiarism_checks");

                    b.ToTable("seo_plagiarism_checks", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_language");

                    b.Property<string>("DefaultLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_location");

                    b.Property<bool>("GscConnected")
                        .HasColumnType("boolean")
                        .HasColumnName("gsc_connected");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_seo_projects");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_seo_projects_org_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_seo_projects_user_id");

                    b.ToTable("seo_projects", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoPublishedPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<DateTimeOffset?>("LastAuditAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_audit_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("TargetKeyword")
                        .HasColumnType("text")
                        .HasColumnName("target_keyword");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int?>("WordPressPostId")
                        .HasColumnType("integer")
                        .HasColumnName("word_press_post_id");

                    b.HasKey("Id")
                        .HasName("pk_seo_published_pages");

                    b.HasIndex("ProjectId", "Url")
                        .IsUnique()
                        .HasDatabaseName("ix_seo_published_pages_project_id_url");

                    b.ToTable("seo_published_pages", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoRankTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Clicks")
                        .HasColumnType("integer")
                        .HasColumnName("clicks");

                    b.Property<decimal>("Ctr")
                        .HasColumnType("numeric")
                        .HasColumnName("ctr");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("Impressions")
                        .HasColumnType("integer")
                        .HasColumnName("impressions");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keyword");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("page_url");

                    b.Property<decimal>("Position")
                        .HasColumnType("numeric")
                        .HasColumnName("position");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_seo_rank_tracking");

                    b.ToTable("seo_rank_tracking", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("report_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_seo_reports");

                    b.ToTable("seo_reports", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoSerpDeepCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keyword");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer")
                        .HasColumnName("result_count");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("results_json");

                    b.Property<string>("TermMatrixJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("term_matrix_json");

                    b.HasKey("Id")
                        .HasName("pk_seo_serp_deep_cache");

                    b.HasIndex("Keyword", "Location", "ResultCount")
                        .IsUnique()
                        .HasDatabaseName("ix_seo_serp_deep_cache_keyword_location_result_count");

                    b.ToTable("seo_serp_deep_cache", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoSerpResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FeaturedSnippet")
                        .HasColumnType("text")
                        .HasColumnName("featured_snippet");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keyword");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("PeopleAlsoAskJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("people_also_ask_json");

                    b.Property<string>("RelatedSearchesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("related_searches_json");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("results_json");

                    b.Property<string>("SerpFeaturesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serp_features_json");

                    b.HasKey("Id")
                        .HasName("pk_seo_serp_results");

                    b.HasIndex("Keyword", "Location", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_seo_serp_results_keyword_location_language_code");

                    b.ToTable("seo_serp_results", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoSiteAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<decimal?>("OverallScore")
                        .HasColumnType("numeric")
                        .HasColumnName("overall_score");

                    b.Property<int>("PagesCrawled")
                        .HasColumnType("integer")
                        .HasColumnName("pages_crawled");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_seo_site_audits");

                    b.ToTable("seo_site_audits", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoSiteAuditPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CrawledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("crawled_at");

                    b.Property<string>("IssuesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issues_json");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("SiteAuditId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_audit_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_seo_site_audit_pages");

                    b.HasIndex("SiteAuditId")
                        .HasDatabaseName("ix_seo_site_audit_pages_site_audit_id");

                    b.ToTable("seo_site_audit_pages", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoSitePageInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CrawledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("crawled_at");

                    b.Property<string>("H1")
                        .HasColumnType("text")
                        .HasColumnName("h1");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer")
                        .HasColumnName("word_count");

                    b.HasKey("Id")
                        .HasName("pk_seo_site_page_inventory");

                    b.HasIndex("ProjectId", "Url")
                        .IsUnique()
                        .HasDatabaseName("ix_seo_site_page_inventory_project_id_url");

                    b.ToTable("seo_site_page_inventory", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<string>("PaypalSubscriptionId")
                        .HasColumnType("text")
                        .HasColumnName("paypal_subscription_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_seo_subscriptions");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_seo_subscriptions_user_id");

                    b.ToTable("seo_subscriptions", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoTopicalMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClustersJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clusters_json");

                    b.Property<string>("ContentGapsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_gaps_json");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_seo_topical_maps");

                    b.ToTable("seo_topical_maps", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoUsageCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feature");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_seo_usage_counters");

                    b.HasIndex("UserId", "PeriodStart", "Feature")
                        .IsUnique()
                        .HasDatabaseName("ix_seo_usage_counters_user_id_period_start_feature");

                    b.ToTable("seo_usage_counters", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoWordPressConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<string>("DefaultPostStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_post_status");

                    b.Property<byte[]>("EncryptedAppPassword")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_app_password");

                    b.Property<byte[]>("EncryptionIv")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encryption_iv");

                    b.Property<byte[]>("EncryptionTag")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encryption_tag");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("site_url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_seo_wordpress_connections");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_seo_wordpress_connections_project_id");

                    b.ToTable("seo_wordpress_connections", "geek_seo");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoCompetitorPage", b =>
                {
                    b.HasOne("GeekApplication.Entities.Seo.SeoSerpResult", "SerpResult")
                        .WithMany("CompetitorPages")
                        .HasForeignKey("SerpResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seo_competitor_pages_seo_serp_results_serp_result_id");

                    b.Navigation("SerpResult");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoContentDocument", b =>
                {
                    b.HasOne("GeekApplication.Entities.Seo.SeoProject", "Project")
                        .WithMany("ContentDocuments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seo_content_documents_seo_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoContentPerformanceSnapshot", b =>
                {
                    b.HasOne("GeekApplication.Entities.Seo.SeoPublishedPage", "PublishedPage")
                        .WithMany()
                        .HasForeignKey("PublishedPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seo_content_performance_snapshots_seo_published_pages_publi");

                    b.Navigation("PublishedPage");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoGeoMentionSnapshot", b =>
                {
                    b.HasOne("GeekApplication.Entities.Seo.SeoGeoTrackingQuery", "Query")
                        .WithMany("Snapshots")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seo_geo_mention_snapshots_seo_geo_tracking_queries_query_id");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoOrganizationMember", b =>
                {
                    b.HasOne("GeekApplication.Entities.Seo.SeoOrganization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seo_organization_members_seo_organizations_org_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoProject", b =>
                {
                    b.HasOne("GeekApplication.Entities.Seo.SeoOrganization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_seo_projects_seo_organizations_org_id");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoSiteAuditPage", b =>
                {
                    b.HasOne("GeekApplication.Entities.Seo.SeoSiteAudit", "SiteAudit")
                        .WithMany("Pages")
                        .HasForeignKey("SiteAuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seo_site_audit_pages_seo_site_audits_site_audit_id");

                    b.Navigation("SiteAudit");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoGeoTrackingQuery", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoOrganization", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoProject", b =>
                {
                    b.Navigation("ContentDocuments");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoSerpResult", b =>
                {
                    b.Navigation("CompetitorPages");
                });

            modelBuilder.Entity("GeekApplication.Entities.Seo.SeoSiteAudit", b =>
                {
                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
