ALTER TABLE devices_oauth ADD COLUMN IF NOT EXISTS public_key TEXT;
ALTER TABLE devices_oauth ADD COLUMN IF NOT EXISTS trusted_until TIMESTAMPTZ;
ALTER TABLE devices_oauth ADD COLUMN IF NOT EXISTS challenge_nonce TEXT;
ALTER TABLE devices_oauth ADD COLUMN IF NOT EXISTS challenge_expires_at TIMESTAMPTZ;
ALTER TABLE devices_oauth ADD COLUMN IF NOT EXISTS is_revoked BOOLEAN NOT NULL DEFAULT FALSE;
